### ISSUE TITLE
1차 QA 수정 - 기획 by 고민

### ISSUE THREAD

**Issue by gom1n** [PomeTeam/POME_iOS#250]
## 💡 issue
1차 QA 수정 - 기획 by 고민

### [회원가입 - 프로필 생성]
- [x]  카메라 미노출
- [x]  카메라 허용 메세지 설정
- [x] 닉네임 > 입력하지 않았을 시 에러메세지 제거
### [목표]
- [x]  완료된 목표가 목표 보관함에 있을 경우 **동일한 목표카테고리명으로 등록 불가(목표 보관함에 있는거는 중복에서 제외해야함)**
   - **서버에 문의**
- [x] 목표10개 초과시 아예 등록 페이지 이동x → 등록 불가 바텀시트 띄우기
- [x] 토큰 발급 후 api 호출
### [기록]
- [x] 기록카드, 감정기록 카드에서도 감정 기록 볼 수 있게함
### [마이페이지]
- [x] 마시멜로 툴팁 연결
https://few-horse-2aa.notion.site/a4a1084333f94e20a30077526be73411
- [x] 오픈소스 라이센스 페이지 이동 **html파일 문의**
- [x] 버전정보 앱스토어 이동 
- [x] 마시멜로우 레벨 설정 (수정한 값도 포함하면 안됨) **서버에 문의**

**Comment by dev-muuu** [comment]
스와이프시 이전 화면 이동은 구현해놨습니다~
추가로 로그인시 rootViewController TabBarController로 바꾸는 것도 되어있습니다!
